# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-01-24 04:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostOfficeEnabler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_enabled', models.BooleanField(default=False, help_text='Should emails be sent to users? If enabled it will send the queued emails.', verbose_name='Email sending enabled')),
            ],
        ),
    ]
