# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2017-02-22 04:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post_office_enabler', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postofficeenabler',
            options={'verbose_name_plural': 'Post Office Enabler'},
        ),
    ]
